### ISSUE TITLE
Alessandra Zorzi can use Grizzled

### ISSUE THREAD

**Issue by Handelblatt-SAP** [Kamalisk/arkhamdb#646]
I had an email correspondence with FFG.
By now "Grizzled" no legal card in Alessandra Zorzi deckbuilding on ArkhamDB.
Can somebody please change that?

```

Hello ****,
Thank you for your interest in Arkham Horror: The Card Game. 
---------- ---------- --------- --------- ---------

To answer your question(s):
Yes, Alessandra Zorzi can take Grizzled.

---------- ---------- --------- --------- ---------
Feel free to reach out to us if any more questions arise!

Sincerely, 
Alex Werner, FFG Game Rules Specialist
Rules questions and their answers are reviewed by both the Arkham Horror: The Card Game design team and the Game Rules Specialist.

```

**Comment by zzorba** [comment]
This has been fixed now

**Comment by LaszloKoller** [comment]
> This has been fixed now

It seems as if _Grizzled_ still does not appear in Alessandra Zorzi's usable cards list:

![image](https://github.com/Kamalisk/arkhamdb/assets/6751481/fffc5781-697b-4ce8-9946-35e9a4f3469a)
